---
galaxy_info:
  role_name: jvb_rtcstats_push
  author: Aaron van Meerten
  description: install and configure rtc stats pusher for videobridge
  license: Apache License Version 2.0
  min_ansible_version: '6.6.0'
  platforms:
    - name: Ubuntu
      releases:
        - focal
        - jammy
dependencies:
  - { role: nodejs, when: jvb_rtcstats_push_install_flag }
