---
- name: Service configuration
  ansible.builtin.template:
    mode: 0644
    src: service.config.j2
    dest: "{{ jvb_rtcstats_push_config_path }}"

- name: Configure systemd script for service
  ansible.builtin.template:
    mode: 0644
    src: systemd.j2
    dest: "/lib/systemd/system/{{ jvb_rtcstats_push_service_name }}.service"

- name: Start service and set it enabled
  ansible.builtin.service:
    name: "{{ jvb_rtcstats_push_service_name }}"
    state: started
    enabled: true
  when: jvb_rtcstats_enabled
