---
- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - install
    - redhat
    - debian
    - collector

- name: Write telegraf.conf file with WF config
  ansible.builtin.template:
    src: telegraf.conf.wfcopy.j2
    dest: "{{ telegraf_main_config }}"
    mode: 0644
  notify: Restart telegraf
  tags:
    - install
    - redhat
    - debian
    - collector
    - configure

- name: Create Wavefront output plugin config 10-wavefront.conf
  ansible.builtin.template:
    src: 10-wavefront.conf.j2
    dest: "{{ telegraf_wavefront_output_plugin_config }}"
    mode: 0644
  notify: Restart telegraf
  tags:
    - install
    - redhat
    - debian
    - collector
    - configure

- name: Create Prometheus output plugin config 20-prometheus.conf
  ansible.builtin.template:
    src: 20-prometheus.conf.j2
    dest: "{{ telegraf_prometheus_output_plugin_config }}"
    mode: 0644
  notify: Restart telegraf
  tags:
    - install
    - redhat
    - debian
    - collector
    - configure

- name: Create systemd telegraf service overrides directory
  ansible.builtin.file:
    mode: 0755
    path: /etc/systemd/system/telegraf.service.d
    state: directory

- name: Set systemd telegraf service overrides
  ansible.builtin.copy:
    dest: /etc/systemd/system/telegraf.service.d/50-oomscoreadjust.conf
    mode: 0644
    owner: root
    content: |
      [Service]
      OOMScoreAdjust=1000
  register: systemd_telegraf_service_override

- name: Run systemd daemon-reload if the telegraf service override was changed
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_telegraf_service_override.changed

- name: Ensure telegraf is running
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true
