---
jigasi_brewery_domain: "auth.{{ environment_domain_name }}"
# Note: avoid capital letters and special chars because prosody lowers/encodes them in the filename.
jigasi_brewery_username_A: "jigasia"
jigasi_brewery_username_B: "jigasib"
jigasi_brewery_path_A: "/var/lib/prosody/{{ jigasi_brewery_domain | regex_replace('\\.', '%2e') |
  regex_replace('-', '%2d') }}/accounts/{{ jigasi_brewery_username_A }}.dat"
jigasi_brewery_path_B: "/var/lib/prosody/{{ jigasi_brewery_domain | regex_replace('\\.', '%2e') |
  regex_replace('-', '%2d') }}/accounts/{{ jigasi_brewery_username_B }}.dat"
# Note: avoid capital letters and special chars because prosody lowers/encodes them in the filename.
jigasi_transcriber_domain: "recorder.{{ environment_domain_name }}"
jigasi_transcriber_username_A: "transcribera"
jigasi_transcriber_path_A: "/var/lib/prosody/{{ jigasi_transcriber_domain | regex_replace('\\.', '%2e') |
  regex_replace('-', '%2d') }}/accounts/{{ jigasi_transcriber_username_A }}.dat"
jigasi_transcriber_username_B: "transcriberb"
jigasi_transcriber_path_B: "/var/lib/prosody/{{ jigasi_transcriber_domain | regex_replace('\\.', '%2e') |
  regex_replace('-', '%2d') }}/accounts/{{ jigasi_transcriber_username_B }}.dat"