---
galaxy_info:
  author: Aaron van Meerten
  description: configure coturn
  license: Apache License Version 2.0
  min_ansible_version: '6.6.0'
  platforms:
    - name: Ubuntu
      releases:
        - focal
        - jammy
dependencies:
  - {role: jitsi-repo}
  - {role: monit}
