---
- name: Main
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  strategy: free
  vars_files:
    - secrets/jigasi.yml
    - config/vars.yml
    - sites/{{ hcv_environment }}/vars.yml

  roles:
    - { role: "jigasi-auth", tags: "auth" }